trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'Serilog.TestLogger.csproj'
    includesymbols: true
    versioningScheme: 'off'



